{
 "title": "OMB Workers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "benchmark", "label": "Benchmark", "query": { "query": "label_values(benchmark)" } },
   { "name": "az", "label": "az", "query": { "query": "label_values(az)" } }
  ]
 },
 "panels": [
  { "title": "Benchmark", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total bytes sent/received",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(benchmark_producer_bytes_sent{benchmark=\"$benchmark\", az=~\"$az\"}[$__rate_interval]))",
     "legendFormat": "bytes sent"
    },
    {
     "expr": "sum(rate(benchmark_consumer_bytes_recv{benchmark=\"$benchmark\", az=~\"$az\"}[$__rate_interval]))",
     "legendFormat": "bytes recv"
    }
   ]
  },
  {
   "title": "End to end Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "benchmark_consumer_e2e_latency{benchmark=\"$benchmark\", quantile=\"0.5\"} > 0",
     "legendFormat": "p50 {{host}}"
    },
    {
     "expr": "benchmark_consumer_e2e_latency{benchmark=\"$benchmark\", quantile=\"0.95\", az=~\"$az\"} > 0",
     "legendFormat": "p95 {{host}}"
    },
    {
     "expr": "benchmark_consumer_e2e_latency{benchmark=\"$benchmark\", quantile=\"0.99\", az=~\"$az\"} > 0",
     "legendFormat": "p99 {{host}}"
    },
    {
     "expr": "benchmark_consumer_e2e_latency{benchmark=\"$benchmark\", quantile=\"0.999\", az=~\"$az\"} > 0",
     "legendFormat": "p999 {{host}}"
    },
    {
     "expr": "benchmark_consumer_e2e_latency{benchmark=\"$benchmark\", quantile=\"1.0\", az=~\"$az\"} > 0",
     "legendFormat": "max {{host}}"
    }
   ]
  },
  {
   "title": "Produce Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "benchmark_producer_produce_latency{benchmark=\"$benchmark\", success=\"true\", quantile=\"0.5\", az=~\"$az\"} > 0",
     "legendFormat": "p50 {{host}}"
    },
    {
     "expr": "benchmark_producer_produce_latency{benchmark=\"$benchmark\", success=\"true\", quantile=\"0.95\", az=~\"$az\"} > 0",
     "legendFormat": "p95 {{host}}"
    },
    {
     "expr": "benchmark_producer_produce_latency{benchmark=\"$benchmark\", success=\"true\", quantile=\"0.99\", az=~\"$az\"} > 0",
     "legendFormat": "p99 {{host}} "
    },
    {
     "expr": "benchmark_producer_produce_latency{benchmark=\"$benchmark\", success=\"true\", quantile=\"0.999\", az=~\"$az\"} > 0",
     "legendFormat": "p999 {{host}}"
    },
    {
     "expr": "benchmark_producer_produce_latency{benchmark=\"$benchmark\", success=\"true\", quantile=\"1.0\", az=~\"$az\"} > 0",
     "legendFormat": "max {{host}}"
    }
   ]
  },
  {
   "title": "Publish Delay latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "benchmark_producer_producer_delay_latency{quantile=\"0.5\", success=\"true\", benchmark=\"$benchmark\"} > 0",
     "legendFormat": "p50 {{host}}"
    },
    {
     "expr": "benchmark_producer_producer_delay_latency{quantile=\"0.95\", success=\"true\", benchmark=\"$benchmark\"} > 0",
     "legendFormat": "p95 {{host}}"
    },
    {
     "expr": "benchmark_producer_producer_delay_latency{quantile=\"0.99\", success=\"true\", benchmark=\"$benchmark\"} > 0",
     "legendFormat": "p99 {{host}}"
    },
    {
     "expr": "benchmark_producer_producer_delay_latency{quantile=\"0.999\", success=\"true\", benchmark=\"$benchmark\"} > 0",
     "legendFormat": "p999 {{host}}"
    },
    {
     "expr": "benchmark_producer_producer_delay_latency{quantile=\"1.0\", success=\"true\", benchmark=\"$benchmark\"} > 0",
     "legendFormat": "p100 {{host}}"
    }
   ]
  },
  {
   "title": "Kafka Producer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request size (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_request_size_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Request size (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_request_size_max{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Request rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_request_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Batch size (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_batch_size_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Batch size (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_batch_size_max{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Records per request (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_records_per_request_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Record Queue time (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_queue_time_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Record Queue time (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_queue_time_max{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Record send rate per topic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_topic_metrics_record_send_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}->{{topic}}"
      }
     ]
    },
    {
     "title": "Request time (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_request_latency_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Request time (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_request_latency_max{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Compression rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_compression_rate_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Request Latency per node (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_node_metrics_request_latency_avg{benchmark=\"$benchmark\"}",
       "legendFormat": "{{host}} {{client_id}} {{node_id}}"
      }
     ]
    },
    {
     "title": "Request Latency per node (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_node_metrics_request_latency_max{benchmark=\"$benchmark\"}",
       "legendFormat": "{{host}} {{client_id}} {{node_id}}"
      }
     ]
    },
    {
     "title": "Metadata age",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_metadata_age{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Outgoing byte rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_outgoing_byte_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Incoming byte rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_incoming_byte_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Metadata wait time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_metadata_wait_time_ns{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Record sent rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_send_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Record retry rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_retry_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Record Error rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_error_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "IO time (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_io_time_ns_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "IO wait time (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_io_wait_time_ns_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Network IO rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_network_io_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Produce Throttle time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_produce_throttle_time_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Bufferpool wail time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(kafka_producer_producer_metrics_bufferpool_wait_time_ns{benchmark=\"$benchmark\", az=~\"$az\"}[$__rate_interval])",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Batch Split rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 92 },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_batch_split_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_connection_count{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Connection creation rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_connection_creation_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch latency (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Commit latency (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_commit_latency_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Rebalance latency avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_rebalance_latency_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch size (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_size_avg{topic!=\"\", benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}} <- {{topic}}"
      }
     ]
    },
    {
     "title": "Fetch size (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_size_max{topic!=\"\", benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}} <- {{topic}}"
      }
     ]
    },
    {
     "title": "Rebalance latency (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_rebalance_latency_max{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Records batch size (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_size_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Records batch size (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_size_max{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Time between poll (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_time_between_poll_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Outgoing byte rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_outgoing_byte_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Incoming byte rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_incoming_byte_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Time between poll (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_time_between_poll_max{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Request rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_request_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Response rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_response_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Committed time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_committed_time_ns{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Assigned Partitions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_assigned_partitions{benchmark=\"$benchmark\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Bytes consumed per sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{topic!=\"\", benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}} <- {{topic}}"
      }
     ]
    },
    {
     "title": "Requests in fligh",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_requests_in_flight{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Select rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_select_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Join rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_join_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Commit rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_commit_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Heartbeat rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_heartbeat_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Sync rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_sync_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Network IO rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_network_io_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "IO time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_io_time_ns_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "IO wait time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_io_wait_time_ns_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Commit sync time ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_commit_sync_time_ns{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_connection_count{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Connection creation rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_connection_creation_rate{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Last poll seconds ago",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_last_poll_seconds_ago{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Failed rebalance rate per hour",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 109 },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_failed_rebalance_rate_per_hour{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch throttle time (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 109 },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_throttle_time_avg{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch throttle time (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 109 },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_throttle_time_max{benchmark=\"$benchmark\", az=~\"$az\"}",
       "legendFormat": "{{host}}-{{client_id}}"
      }
     ]
    }
   ]
  }
 ]
}